from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion

TEMPLATES = [
    {
        "clave": "ACTA_CONSTITUTIVA",
        "nombre": "Acta constitutiva y modificaciones",
        "categoria": "BASE_CORPORATIVA",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Establece la existencia legal, socios y objeto social; base de cualquier revisión corporativa.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo", "soporte_documental"],
        "orden": 100,
    },
    {
        "clave": "PODERES_REPRESENTANTES",
        "nombre": "Poderes de representantes legales",
        "categoria": "BASE_CORPORATIVA",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Documento que acredita las facultades vigentes ante notarías y RPC para firmar contratos.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "expediente_externo"],
        "orden": 110,
    },
    {
        "clave": "CUENTAS_BANCARIAS_KYC",
        "nombre": "Contrato de cuentas bancarias y KYC",
        "categoria": "BASE_CORPORATIVA",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Apertura de cuentas, anexos KYC/KYV y actualizaciones con instituciones financieras.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo", "vigencia_inicio"],
        "orden": 120,
    },
    {
        "clave": "NDA_MARCO",
        "nombre": "Contratos marco de confidencialidad",
        "categoria": "BASE_CORPORATIVA",
        "proceso": "OPERACIONES",
        "tipo_empresa": "MIXTA",
        "descripcion": "NDAs con clientes, proveedores estratégicos y desarrolladores que resguardan información.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 130,
    },
    {
        "clave": "AVISO_PRIVACIDAD_TYC",
        "nombre": "Avisos de privacidad y TyC",
        "categoria": "BASE_CORPORATIVA",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Documentos publicados para portales, apps o manejo de datos personales.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo"],
        "orden": 140,
    },
    {
        "clave": "SUMINISTRO_CLIENTES",
        "nombre": "Contrato de compraventa o suministro con clientes",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Define condiciones de entrega, precios, garantías y logística para ventas recurrentes.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 200,
    },
    {
        "clave": "SERVICIOS_CLIENTES",
        "nombre": "Contrato de prestación de servicios a clientes",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Servicios profesionales, mantenimiento, capacitación o marketing con entregables claros.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 210,
    },
    {
        "clave": "CONTRATO_OBRA",
        "nombre": "Contrato de obra a precio alzado o administración",
        "categoria": "CLIENTES",
        "proceso": "OPERACIONES",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Construcción, instalaciones o proyectos tecnológicos con estimaciones y avances.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_fin", "descripcion", "soporte_documental"],
        "orden": 220,
    },
    {
        "clave": "ARRENDAMIENTO_MUEBLES_CLIENTE",
        "nombre": "Arrendamiento de bienes muebles a favor del cliente",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Renta de equipos, maquinaria o vehículos entregados temporalmente a clientes.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 230,
    },
    {
        "clave": "LICENCIA_SOFTWARE_CLIENTE",
        "nombre": "Licencia de uso de software o SaaS",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Cesión temporal de uso de plataformas, contenido o propiedad intelectual.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 240,
    },
    {
        "clave": "COMISION_MERCANTIL",
        "nombre": "Contrato de comisión mercantil o intermediación",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Define comisiones, alcance y comprobación de gestiones de intermediarios.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 250,
    },
    {
        "clave": "DISTRIBUCION_FRANQUICIA",
        "nombre": "Contrato de distribución, franquicia o agencia",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Estructura relaciones de canal, regalías y obligaciones de marca.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 260,
    },
    {
        "clave": "CONVENIO_MODIFICATORIO",
        "nombre": "Convenios modificatorios y adendas",
        "categoria": "CLIENTES",
        "proceso": "VENTAS",
        "tipo_empresa": "MIXTA",
        "descripcion": "Actualiza precios, alcances o entregables de contratos vigentes.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "soporte_documental"],
        "orden": 270,
    },
    {
        "clave": "SUMINISTRO_PROVEEDORES",
        "nombre": "Contrato de suministro con proveedores",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Volúmenes, calidad y logística de materias primas o mercancías.",
        "es_marco": True,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 300,
    },
    {
        "clave": "SERVICIOS_PROVEEDORES",
        "nombre": "Contrato de servicios con proveedores clave",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Consultoría, mantenimiento especializado, seguridad o publicidad.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "fecha_firma", "vigencia_fin", "descripcion"],
        "orden": 310,
    },
    {
        "clave": "ARRENDAMIENTO_INMUEBLES",
        "nombre": "Arrendamiento de inmuebles",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "MIXTA",
        "descripcion": "Renta de oficinas, bodegas o naves industriales para operaciones.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 320,
    },
    {
        "clave": "ARRENDAMIENTO_MAQUINARIA",
        "nombre": "Arrendamiento de maquinaria, vehículos o TI",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Uso operativo de equipos críticos que soportan la producción o logística.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 330,
    },
    {
        "clave": "SERVICIOS_TECNOLOGICOS",
        "nombre": "Servicios tecnológicos y telecom",
        "categoria": "PROVEEDORES",
        "proceso": "OPERACIONES",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Hosting, nube, licencias, soporte y telecomunicaciones críticas.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "expediente_externo"],
        "orden": 340,
    },
    {
        "clave": "LOGISTICA_TRANSPORTE",
        "nombre": "Contrato de logística, almacenamiento y transporte",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Tercerización de cadena logística, inventarios y entregas.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 350,
    },
    {
        "clave": "CONTRATO_SEGUROS",
        "nombre": "Contratos de seguros empresariales",
        "categoria": "PROVEEDORES",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Coberturas de daños, RC, flotillas o seguros de crédito.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 360,
    },
    {
        "clave": "SUBCONTRATACION_REPSE",
        "nombre": "Contratos de subcontratación especializada (REPSE)",
        "categoria": "PROVEEDORES",
        "proceso": "COMPRAS",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Servicios especializados con evidencia de registro REPSE y entregables.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 370,
    },
    {
        "clave": "CONTRATO_TRABAJO_INDIVIDUAL",
        "nombre": "Contratos individuales de trabajo",
        "categoria": "CAPITAL_HUMANO",
        "proceso": "NOMINA",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Definen puesto, salario y prestaciones de cada colaborador.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 400,
    },
    {
        "clave": "CONTRATO_COLECTIVO",
        "nombre": "Contrato colectivo y acuerdos sindicales",
        "categoria": "CAPITAL_HUMANO",
        "proceso": "NOMINA",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Condiciones pactadas con sindicatos, revisiones salariales y prestaciones.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 410,
    },
    {
        "clave": "SERVICIOS_INDEPENDIENTES",
        "nombre": "Prestadores de servicios independientes",
        "categoria": "CAPITAL_HUMANO",
        "proceso": "NOMINA",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Honorarios asimilados o especialistas sin subordinación directa.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "soporte_documental"],
        "orden": 420,
    },
    {
        "clave": "CONVENIOS_PERSONAL_CLAVE",
        "nombre": "Convenios de confidencialidad y no competencia",
        "categoria": "CAPITAL_HUMANO",
        "proceso": "NOMINA",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Protege know-how y cartera de clientes frente a personal estratégico.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_fin", "descripcion"],
        "orden": 430,
    },
    {
        "clave": "POLITICAS_REGLAMENTO",
        "nombre": "Políticas y reglamento interior de trabajo",
        "categoria": "CAPITAL_HUMANO",
        "proceso": "NOMINA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Lineamientos internos, jornadas, viáticos y disciplina firmados de recibido.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo"],
        "orden": 440,
    },
    {
        "clave": "CREDITO_SIMPLE",
        "nombre": "Contratos de apertura de crédito",
        "categoria": "FINANCIERO",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Créditos simples, refaccionarios o revolventes con bancos u otros acreedores.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 500,
    },
    {
        "clave": "ARRENDAMIENTO_FINANCIERO",
        "nombre": "Contratos de arrendamiento financiero",
        "categoria": "FINANCIERO",
        "proceso": "TESORERIA",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Leasing de activos fijos con plazos, valor residual y calendario de pagos.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 510,
    },
    {
        "clave": "CONTRATO_MUTUO",
        "nombre": "Contratos de mutuo con o sin garantía",
        "categoria": "FINANCIERO",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Préstamos entre socios o partes relacionadas con tasas y plazos definidos.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 520,
    },
    {
        "clave": "FACTOR_AJE",
        "nombre": "Contratos de factoraje o cesión de derechos",
        "categoria": "FINANCIERO",
        "proceso": "TESORERIA",
        "tipo_empresa": "COMERCIAL",
        "descripcion": "Cesión de cuentas por cobrar, CFDI o pagarés para liquidez inmediata.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["fecha_firma", "vigencia_fin", "descripcion"],
        "orden": 530,
    },
    {
        "clave": "GARANTIAS_REALES",
        "nombre": "Convenios de garantías reales y personales",
        "categoria": "FINANCIERO",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Hipotecas, prendas o avales que respaldan obligaciones financieras.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo", "soporte_documental"],
        "orden": 540,
    },
    {
        "clave": "COMPRA_MAQUINARIA",
        "nombre": "Compraventa de maquinaria y equipo",
        "categoria": "ACTIVOS",
        "proceso": "OPERACIONES",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Adquisición de equipo productivo con especificaciones técnicas y garantías.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "fecha_firma", "descripcion", "soporte_documental"],
        "orden": 600,
    },
    {
        "clave": "COMPRA_INMUEBLES",
        "nombre": "Compraventa o promesa de inmuebles",
        "categoria": "ACTIVOS",
        "proceso": "OPERACIONES",
        "tipo_empresa": "MIXTA",
        "descripcion": "Compra de terrenos, oficinas o plantas con entrega y escrituración.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "fecha_firma", "descripcion", "expediente_externo"],
        "orden": 610,
    },
    {
        "clave": "MANTENIMIENTO_ACTIVOS",
        "nombre": "Mantenimiento preventivo y correctivo",
        "categoria": "ACTIVOS",
        "proceso": "OPERACIONES",
        "tipo_empresa": "INDUSTRIAL",
        "descripcion": "Servicios para activos críticos como maquinaria, sistemas o equipo médico.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 620,
    },
    {
        "clave": "LICENCIA_PI",
        "nombre": "Licencia o cesión de PI, marcas y software",
        "categoria": "ACTIVOS",
        "proceso": "OPERACIONES",
        "tipo_empresa": "SERVICIOS",
        "descripcion": "Transfiere o autoriza uso de marcas, patentes, know-how o software.",
        "es_marco": False,
        "requiere_proveedor": True,
        "campos_configurables": ["proveedor", "vigencia_inicio", "vigencia_fin", "expediente_externo"],
        "orden": 630,
    },
    {
        "clave": "FIDEICOMISO_ACTIVOS",
        "nombre": "Fideicomisos inmobiliarios o de administración",
        "categoria": "ACTIVOS",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Estructuras fiduciarias para administrar activos o proyectos.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo", "soporte_documental"],
        "orden": 640,
    },
    {
        "clave": "SERVICIOS_INTRAGRUPO",
        "nombre": "Servicios intragrupo",
        "categoria": "PARTES_RELACIONADAS",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Cargos administrativos, técnicos o financieros entre empresas relacionadas.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 700,
    },
    {
        "clave": "USO_MARCA_PARTES",
        "nombre": "Uso de marca, licencias y regalías entre partes relacionadas",
        "categoria": "PARTES_RELACIONADAS",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Autoriza marcas o asistencia técnica entre compañías del grupo.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion", "expediente_externo"],
        "orden": 710,
    },
    {
        "clave": "CUENTA_CORRIENTE_PARTES",
        "nombre": "Contratos de cuenta corriente entre partes relacionadas",
        "categoria": "PARTES_RELACIONADAS",
        "proceso": "TESORERIA",
        "tipo_empresa": "MIXTA",
        "descripcion": "Registra aportes, retiros e intereses entre empresas del grupo.",
        "es_marco": False,
        "requiere_proveedor": False,
        "campos_configurables": ["vigencia_inicio", "vigencia_fin", "descripcion"],
        "orden": 720,
    },
    {
        "clave": "CONVENIO_ACCIONISTAS",
        "nombre": "Convenios de accionistas",
        "categoria": "PARTES_RELACIONADAS",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Pactos sobre voto, dividendos o restricciones adicionales a los estatutos.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo"],
        "orden": 730,
    },
    {
        "clave": "POLITICA_PRECIOS_TRANSFERENCIA",
        "nombre": "Políticas y estudios de precios de transferencia",
        "categoria": "PARTES_RELACIONADAS",
        "proceso": "GOBIERNO_CORPORATIVO",
        "tipo_empresa": "MIXTA",
        "descripcion": "Documenta metodologías y comparables para sustancia económica y 69-B.",
        "es_marco": True,
        "requiere_proveedor": False,
        "campos_configurables": ["descripcion", "expediente_externo", "soporte_documental"],
        "orden": 740,
    },
]


def seed_templates(apps, schema_editor):
    Template = apps.get_model("materialidad", "ContratoTemplate")
    for data in TEMPLATES:
        Template.objects.update_or_create(
            clave=data["clave"],
            defaults={
                "nombre": data["nombre"],
                "categoria": data["categoria"],
                "proceso": data["proceso"],
                "tipo_empresa": data["tipo_empresa"],
                "descripcion": data["descripcion"],
                "es_marco": data["es_marco"],
                "requiere_proveedor": data["requiere_proveedor"],
                "campos_configurables": data["campos_configurables"],
                "orden": data["orden"],
            },
        )


def unseed_templates(apps, schema_editor):
    Template = apps.get_model("materialidad", "ContratoTemplate")
    Template.objects.filter(clave__in=[item["clave"] for item in TEMPLATES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("materialidad", "0002_contrato"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clave", models.CharField(max_length=64, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("categoria", models.CharField(choices=[('BASE_CORPORATIVA', 'Base corporativa'), ('CLIENTES', 'Clientes / ingresos'), ('PROVEEDORES', 'Proveedores / egresos'), ('CAPITAL_HUMANO', 'Capital humano'), ('FINANCIERO', 'Financiero / crédito'), ('ACTIVOS', 'Activos fijos e intangibles'), ('PARTES_RELACIONADAS', 'Partes relacionadas')], max_length=32)),
                ("proceso", models.CharField(choices=[('COMPRAS', 'Compras'), ('VENTAS', 'Ventas'), ('NOMINA', 'Nómina'), ('TESORERIA', 'Tesorería'), ('OPERACIONES', 'Operaciones'), ('GOBIERNO_CORPORATIVO', 'Gobierno corporativo')], max_length=32)),
                ("tipo_empresa", models.CharField(choices=[('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('SERVICIOS', 'Servicios'), ('MIXTA', 'Mixta')], default='MIXTA', max_length=16)),
                ("descripcion", models.TextField(blank=True)),
                ("es_marco", models.BooleanField(default=False)),
                ("requiere_proveedor", models.BooleanField(default=False)),
                ("campos_configurables", models.JSONField(blank=True, default=list)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "materialidad_contrato_template",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.AddField(
            model_name="contrato",
            name="template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contratos", to="materialidad.contratotemplate"),
        ),
        migrations.RunPython(seed_templates, unseed_templates),
    ]
