# Generated by Django 5.0.2 on 2025-12-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0004_legalreferencesource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ('-vigencia_inicio', 'nombre'), 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='contratotemplate',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Plantilla de contrato', 'verbose_name_plural': 'Plantillas de contrato'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('razon_social',), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('razon_social',), 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameIndex(
            model_name='contrato',
            new_name='materialida_categor_4aadf7_idx',
            old_name='contrato_cat_proc_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_ley_f65d1b_idx',
            old_name='materialida_ley_artic_bce6af_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_tipo_fu_36e392_idx',
            old_name='materialida_tipo_fu_6e4e5c_idx',
        ),
        migrations.RenameIndex(
            model_name='operacion',
            new_name='materialida_estatus_aaa538_idx',
            old_name='materialid_estatus_0e99b1_idx',
        ),
        migrations.RenameIndex(
            model_name='operacion',
            new_name='materialida_fecha_o_cf8aa4_idx',
            old_name='materialid_fecha_o_a2910f_idx',
        ),
        migrations.RenameIndex(
            model_name='operacion',
            new_name='materialida_contrat_388ea6_idx',
            old_name='operacion_contrato_idx',
        ),
    ]
