# Generated by Django 5.0.2 on 2025-12-08 17:34

from django.db import migrations
from psycopg import sql


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0008_dashboardsnapshot'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: _rename_indexes(schema_editor.connection),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _rename_indexes(conn):
    if conn.vendor != 'postgresql':
        return
    renames = [
        ("materialida_contrat_33c3ed_idx", "materialida_contrat_0d5fe3_idx"),
        ("materialida_update_5d8f9e_idx", "materialida_updated_0887f2_idx"),
        ("materiali_tenant__4ab1e6_idx", "materialida_tenant__cef59d_idx"),
    ]
    with conn.cursor() as cursor:
        for old, new in renames:
            cursor.execute(
                sql.SQL("ALTER INDEX IF EXISTS {} RENAME TO {};").format(
                    sql.Identifier(old),
                    sql.Identifier(new),
                )
            )
