# Generated by Django 5.0.2 on 2025-12-08 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("materialidad", "0009_rename_materialida_contrat_33c3ed_idx_materialida_contrat_0d5fe3_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalConsultation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_slug", models.SlugField(max_length=255)),
                ("question", models.TextField()),
                ("context", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("references", models.JSONField(blank=True, default=list)),
                ("ai_model", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "materialidad_legal_consultation",
                "ordering": ("-created_at",),
                "verbose_name": "Consulta legal",
                "verbose_name_plural": "Consultas legales",
                "indexes": [
                    models.Index(fields=["tenant_slug", "created_at"], name="materialida_tenant_chat_idx"),
                ],
            },
        ),
    ]
