# Generated by Django 5.0.2 on 2025-12-08 18:29

from django.db import migrations


def noop(*args, **kwargs):
    """This migration is intentionally left blank to avoid duplicate index renames."""


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0010_legalconsultation'),
    ]

    operations = [
        migrations.RunPython(code=noop, reverse_code=migrations.RunPython.noop),
    ]
