# Generated by Django 5.0.2 on 2025-12-08 20:22

from django.db import migrations

def rename_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    sqls = [
        "ALTER INDEX IF EXISTS materialida_contrat_33c3ed_idx RENAME TO materialida_contrat_0d5fe3_idx;",
        "ALTER INDEX IF EXISTS materialida_update_5d8f9e_idx RENAME TO materialida_updated_0887f2_idx;",
        "ALTER INDEX IF EXISTS materiali_tenant__4ab1e6_idx RENAME TO materialida_tenant__cef59d_idx;",
    ]
    for sql in sqls:
        schema_editor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0011_rename_materialida_contrat_33c3ed_idx_materialida_contrat_0d5fe3_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='contractcitationcache',
                    new_name='materialida_contrat_0d5fe3_idx',
                    old_name='materialida_contrat_33c3ed_idx',
                ),
                migrations.RenameIndex(
                    model_name='contractcitationcache',
                    new_name='materialida_updated_0887f2_idx',
                    old_name='materialida_update_5d8f9e_idx',
                ),
                migrations.RenameIndex(
                    model_name='dashboardsnapshot',
                    new_name='materialida_tenant__cef59d_idx',
                    old_name='materiali_tenant__4ab1e6_idx',
                ),
            ],
        ),
    ]
