# Generated by Django 5.0.2 on 2025-12-08 23:24

from django.db import migrations

def drop_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'materialidad_legal_consultation') THEN
                ALTER TABLE materialidad_legal_consultation
                DROP CONSTRAINT IF EXISTS materialidad_legal_c_user_id_32ae7233_fk_accounts_;
            END IF;
        END$$;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0012_rename_materialida_contrat_33c3ed_idx_materialida_contrat_0d5fe3_idx_and_more'),
    ]

    operations = [
         migrations.RunPython(drop_constraint, reverse_code=migrations.RunPython.noop),
    ]
