# Generated by Django 5.0.2 on 2025-12-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0012_rename_materialida_contrat_33c3ed_idx_materialida_contrat_0d5fe3_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$\n"
                "BEGIN\n"
                "    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'materialidad_legal_consultation') THEN\n"
                "        ALTER TABLE materialidad_legal_consultation\n"
                "        DROP CONSTRAINT IF EXISTS materialidad_legal_c_user_id_32ae7233_fk_accounts_;\n"
                "    END IF;\n"
                "END$$;"
            ),
            reverse_sql=(
                "DO $$\n"
                "BEGIN\n"
                "    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'materialidad_legal_consultation') THEN\n"
                "        ALTER TABLE materialidad_legal_consultation\n"
                "        ADD CONSTRAINT materialidad_legal_c_user_id_32ae7233_fk_accounts_\n"
                "        FOREIGN KEY (user_id) REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;\n"
                "    END IF;\n"
                "END$$;"
            ),
        )
    ]
