# Generated by Django 5.0.2 on 2025-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0017_contract_materiality_fields_and_evidence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidenciamaterial',
            new_name='materialida_tipo_0f9615_idx',
            old_name='materialid_tipo_cr_7bf7ab_idx',
        ),
        migrations.RemoveField(
            model_name='legalconsultation',
            name='is_deduplicated',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='beneficio_economico_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto estimado del beneficio económico (no fiscal)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='beneficio_fiscal_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Beneficio fiscal estimado para validar la razón de negocios', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razon_negocio',
            field=models.TextField(blank=True, help_text='Describe el propósito económico real conforme al art. 5-A CFF'),
        ),
        migrations.AlterField(
            model_name='evidenciamaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidenciamaterial',
            name='tipo',
            field=models.CharField(choices=[('ENTREGABLE', 'Entregable final'), ('BITACORA', 'Bitácora / minuta'), ('COMUNICACION', 'Comunicación'), ('FOTOGRAFIA', 'Evidencia fotográfica')], default='ENTREGABLE', max_length=20),
        ),
    ]
