# Generated by Django 5.0.2 on 2026-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0023_contrato_firma_logistica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciamaterial',
            name='operacion',
        ),
        migrations.RenameIndex(
            model_name='checklist',
            new_name='materialida_tenant__b80a22_idx',
            old_name='materialid_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='checklistitem',
            new_name='materialida_pillar_e80065_idx',
            old_name='materialid_pillar_s_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverablerequirement',
            new_name='materialida_tenant__6de33f_idx',
            old_name='materialid_deliv_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='operacion',
            new_name='materialida_cfdi_es_1b2cbe_idx',
            old_name='operacion_cfdi_spei_idx',
        ),
        migrations.RenameIndex(
            model_name='proveedor',
            new_name='materialida_estatus_3c7c05_idx',
            old_name='proveedor_69b_riesgo_idx',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='nif_aplicable',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='observacion_contable',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='poliza_contable',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_notariado_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='beneficio_economico_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto estimado del beneficio economico (no fiscal)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='beneficio_fiscal_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Beneficio fiscal estimado para validar la razon de negocios', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contacto_responsable',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='lugar_cita',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='notas_logistica',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razon_negocio',
            field=models.TextField(blank=True, help_text='Describe el proposito economico real conforme al art. 5-A CFF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='responsable_logistica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='EvidenciaMaterial',
        ),
    ]
