# Generated by Django 5.0.2 on 2026-01-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0024_remove_evidenciamaterial_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='nif_aplicable',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='operacion',
            name='observacion_contable',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operacion',
            name='poliza_contable',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='EvidenciaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTREGABLE', 'Entregable final'), ('BITACORA', 'Bitacora / minuta'), ('COMUNICACION', 'Comunicacion'), ('FOTOGRAFIA', 'Evidencia fotografica')], default='ENTREGABLE', max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('descripcion', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='materialidad.operacion')),
            ],
            options={
                'verbose_name': 'Evidencia de materialidad',
                'verbose_name_plural': 'Evidencias de materialidad',
                'db_table': 'materialidad_evidencia_material',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tipo', 'created_at'], name='materialid_tipo_cr_7bf7ab_idx')],
            },
        ),
    ]
