# Generated by Django 5.0.2 on 2026-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0027_operacion_entregable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operacionentregable',
            new_name='materialida_operaci_405dd5_idx',
            old_name='materialid_op_2348ef_idx',
        ),
        migrations.RenameIndex(
            model_name='operacionentregable',
            new_name='materialida_codigo_ca223d_idx',
            old_name='materialid_co_3ec61f_idx',
        ),
        migrations.AlterField(
            model_name='operacionentregable',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio'), ('CAPACIDAD_PROVEEDOR', 'Capacidad del proveedor'), ('FECHA_CIERTA', 'Fecha cierta')], default='ENTREGABLES', max_length=32),
        ),
    ]
