# Generated by Django 5.0.2 on 2026-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0028_rename_materialid_op_2348ef_idx_materialida_operaci_405dd5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='registro_publico_folio',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contrato',
            name='registro_publico_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sello_tiempo_acuse_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sello_tiempo_aplicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sello_tiempo_proveedor',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
