# Generated by Django 5.0.2 on 2026-01-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0029_contrato_registro_publico_folio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazonNegocioAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('RESPONSABLE_AREA', 'Responsable del área'), ('COMPLIANCE', 'Compliance / Legal'), ('FISCAL', 'Fiscal'), ('DIRECTOR', 'Dirección')], max_length=32)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=16)),
                ('comentario', models.TextField(blank=True, default='')),
                ('evidencia_url', models.URLField(blank=True, default='')),
                ('firmado_por', models.CharField(blank=True, default='', max_length=255)),
                ('firmado_email', models.EmailField(blank=True, default='', max_length=254)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_razon', to='materialidad.contrato')),
            ],
            options={
                'db_table': 'materialidad_razon_negocio_aprobacion',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['contrato', 'estado'], name='materialida_contrat_afbf26_idx')],
            },
        ),
    ]
