# Generated by Django 5.0.2 on 2026-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0030_razonnegocioaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='razon_negocio_aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='razon_negocio_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=16),
        ),
        migrations.AddField(
            model_name='contrato',
            name='razon_negocio_ultimo_rol',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
