# Generated by Django 5.0.2 on 2026-01-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0031_contrato_razon_negocio_aprobado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='capacidad_economica_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad económica mensual estimada (MXN)', max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=128)),
                ('banco', models.CharField(blank=True, default='', max_length=128)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=32)),
                ('clabe', models.CharField(blank=True, default='', max_length=18)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso mexicano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='MXN', max_length=3)),
                ('titular', models.CharField(blank=True, default='', max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='materialidad.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'materialidad_cuenta_bancaria',
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('archivo_url', models.URLField(blank=True, default='')),
                ('hash_archivo', models.CharField(blank=True, default='', max_length=128)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_abonos', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_cargos', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to='materialidad.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'verbose_name_plural': 'Estados de cuenta',
                'db_table': 'materialidad_estado_cuenta',
                'ordering': ('-periodo_fin',),
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tipo', models.CharField(choices=[('ABONO', 'Abono'), ('CARGO', 'Cargo')], max_length=8)),
                ('referencia', models.CharField(blank=True, default='', max_length=64)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('cuenta_contraparte', models.CharField(blank=True, default='', max_length=32)),
                ('banco_contraparte', models.CharField(blank=True, default='', max_length=128)),
                ('nombre_contraparte', models.CharField(blank=True, default='', max_length=255)),
                ('spei_referencia', models.CharField(blank=True, default='', max_length=64)),
                ('categoria', models.CharField(blank=True, default='', max_length=64)),
                ('es_circular', models.BooleanField(default=False)),
                ('alerta_capacidad', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='materialidad.cuentabancaria')),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='materialidad.estadocuenta')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'db_table': 'materialidad_movimiento_bancario',
                'ordering': ('-fecha', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OperacionConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTO', 'Auto'), ('MANUAL', 'Manual'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=16)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion', to='materialidad.movimientobancario')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='materialidad.operacion')),
            ],
            options={
                'verbose_name': 'Conciliación de operación',
                'verbose_name_plural': 'Conciliaciones de operación',
                'db_table': 'materialidad_operacion_conciliacion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['empresa', 'moneda'], name='materialida_empresa_0aaaea_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocuenta',
            index=models.Index(fields=['cuenta', 'periodo_fin'], name='materialida_cuenta__880d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['cuenta', 'fecha'], name='mov_cuenta_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['spei_referencia'], name='mov_spei_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionconciliacion',
            index=models.Index(fields=['operacion', 'estado'], name='conc_op_estado_idx'),
        ),
    ]
