# Generated by Django 5.0.2 on 2026-01-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0034_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deliverablerequirement',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio')], default='ENTREGABLES', max_length=32),
        ),
        migrations.AlterField(
            model_name='operacionentregable',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio')], default='ENTREGABLES', max_length=32),
        ),
    ]
