# Generated by Django 5.0.2 on 2026-01-27 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0035_alter_auditlog_id_alter_checklistitem_pillar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TransaccionIntercompania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESTAMO', 'Préstamo'), ('SERVICIO', 'Prestación de servicio'), ('VENTA', 'Venta de bienes'), ('REGALIAS', 'Regalías'), ('ARRENDAMIENTO', 'Arrendamiento'), ('OTRO', 'Otro')], max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_principal', models.DecimalField(decimal_places=2, help_text='Monto principal de la transacción', max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('MXN', 'Peso mexicano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='MXN', max_length=3)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de interés anual (si aplica)', max_digits=6, null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la transacción')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento', null=True)),
                ('fecha_liquidacion', models.DateField(blank=True, help_text='Fecha de liquidación efectiva', null=True)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, help_text='Saldo pendiente de pago', max_digits=19)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('LIQUIDADO', 'Liquidado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=16)),
                ('num_operacion_interna', models.CharField(blank=True, help_text='Número de operación interna', max_length=64)),
                ('razon_negocio', models.TextField(blank=True, help_text='Justificación económica de la transacción intercompañía')),
                ('beneficio_grupo', models.TextField(blank=True, help_text='Beneficio para el grupo corporativo')),
                ('estudio_precios_transferencia', models.BooleanField(default=False, help_text='¿Se cuenta con estudio de precios de transferencia?')),
                ('metodo_valuacion', models.CharField(blank=True, help_text='Método de valuación aplicado (CUP, RPM, CPM, etc.)', max_length=128)),
                ('archivo_estudio_url', models.URLField(blank=True, help_text='URL del estudio de precios de transferencia')),
                ('requiere_atencion', models.BooleanField(default=False)),
                ('notas_alerta', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato que documenta esta transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_intercompania', to='materialidad.contrato')),
                ('empresa_destino', models.ForeignKey(help_text='Empresa que recibe el préstamo o servicio', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_recibidas', to='materialidad.empresa')),
                ('empresa_origen', models.ForeignKey(help_text='Empresa que otorga el préstamo o presta el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_enviadas', to='materialidad.empresa')),
            ],
            options={
                'verbose_name': 'Transacción intercompañía',
                'verbose_name_plural': 'Transacciones intercompañía',
                'db_table': 'materialidad_transaccion_intercompania',
                'ordering': ('-fecha_inicio',),
                'indexes': [models.Index(fields=['empresa_origen', 'empresa_destino'], name='materialida_empresa_a3b866_idx'), models.Index(fields=['estado', 'fecha_vencimiento'], name='materialida_estado_32cbe7_idx'), models.Index(fields=['tipo', 'estado'], name='materialida_tipo_46237b_idx')],
            },
        ),
    ]
