# Generated by Django 5.0.2 on 2026-02-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0037_contractdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField(help_text='Redacción de la cláusula lista para insertar en contratos')),
                ('resumen', models.TextField(blank=True, help_text='Descripción breve de qué cubre esta cláusula')),
                ('categorias', models.JSONField(blank=True, default=list, help_text='Lista de categorías de contrato donde aplica (BASE_CORPORATIVA, PROVEEDORES, etc.)')),
                ('procesos', models.JSONField(blank=True, default=list, help_text='Lista de procesos donde aplica (COMPRAS, OPERACIONES, etc.)')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=8)),
                ('tips_redline', models.JSONField(blank=True, default=list, help_text='Consejos para revisión de redlines')),
                ('palabras_clave', models.JSONField(blank=True, default=list, help_text='Palabras clave para búsqueda y matching')),
                ('prioridad', models.PositiveIntegerField(default=3, help_text='Mayor = más relevante (1-10)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión de la cláusula para trazabilidad')),
                ('es_curada', models.BooleanField(default=False, help_text='Cláusula curada por el equipo legal (visible para todos los tenants)')),
                ('creado_por', models.CharField(blank=True, default='', help_text='Email o identificador del usuario que creó la cláusula', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de cláusula',
                'verbose_name_plural': 'Plantillas de cláusula',
                'db_table': 'materialidad_clause_template',
                'ordering': ('-prioridad', 'titulo'),
            },
        ),
        migrations.RenameIndex(
            model_name='contractdocument',
            new_name='materialida_contrat_844c04_idx',
            old_name='materialid_contrato_2b9b57_idx',
        ),
        migrations.RenameIndex(
            model_name='contractdocument',
            new_name='materialida_created_bfc8ee_idx',
            old_name='materialid_created_0f3aa9_idx',
        ),
        migrations.AddField(
            model_name='contratotemplate',
            name='contrato_base',
            field=models.ForeignKey(blank=True, help_text='Contrato depurado que sirve como base para futuras generaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_derivados', to='materialidad.contrato'),
        ),
        migrations.AddField(
            model_name='contratotemplate',
            name='documento_base',
            field=models.ForeignKey(blank=True, help_text='Versión específica del documento usada como referencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_derivados', to='materialidad.contractdocument'),
        ),
        migrations.AddField(
            model_name='contratotemplate',
            name='markdown_base',
            field=models.TextField(blank=True, default='', help_text='Texto markdown depurado (anonimizado) que se inyecta como contexto al prompt AI'),
        ),
        migrations.AddField(
            model_name='clausetemplate',
            name='contrato_origen',
            field=models.ForeignKey(blank=True, help_text='Contrato del cual se extrajo esta cláusula (aprendizaje orgánico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clausulas_derivadas', to='materialidad.contrato'),
        ),
        migrations.AddIndex(
            model_name='clausetemplate',
            index=models.Index(fields=['nivel_riesgo', 'activo'], name='materialida_nivel_r_fff137_idx'),
        ),
        migrations.AddIndex(
            model_name='clausetemplate',
            index=models.Index(fields=['es_curada', 'activo'], name='materialida_es_cura_732c28_idx'),
        ),
    ]
