# Generated by Django 5.0.2 on 2026-02-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0039_seed_clause_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fedatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del fedatario', max_length=255)),
                ('tipo', models.CharField(choices=[('NOTARIO', 'Notario público'), ('CORREDOR', 'Corredor público'), ('OTRO', 'Otro fedatario')], default='NOTARIO', max_length=16)),
                ('numero_notaria', models.CharField(blank=True, help_text='Número de notaría o correduría', max_length=32)),
                ('estado', models.CharField(help_text='Entidad federativa', max_length=128)),
                ('ciudad', models.CharField(blank=True, max_length=128)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa de la notaría')),
                ('telefono', models.CharField(blank=True, max_length=64)),
                ('telefono_alterno', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('cedula_profesional', models.CharField(blank=True, max_length=32)),
                ('horario_atencion', models.CharField(blank=True, help_text='Ej. L-V 9:00-18:00', max_length=128)),
                ('contacto_asistente', models.CharField(blank=True, help_text='Nombre del asistente o contacto alterno', max_length=255)),
                ('contacto_asistente_tel', models.CharField(blank=True, max_length=64)),
                ('contacto_asistente_email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True, help_text='Observaciones, experiencia previa, recomendaciones')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fedatario',
                'verbose_name_plural': 'Fedatarios',
                'db_table': 'materialidad_fedatario',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='fedatario',
            field=models.ForeignKey(blank=True, help_text='Fedatario seleccionado del catálogo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='materialidad.fedatario'),
        ),
    ]
