# Generated by Django 5.0.2 on 2026-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0041_empresa_proveedor_persona_fisica_moral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(help_text='Razón social (PM) o nombre completo (PF)', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(help_text='Razón social (PM) o nombre completo (PF)', max_length=255),
        ),
    ]
