# Generated by Django 5.0.2 on 2026-02-25 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0042_alter_empresa_razon_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('PROPIETARIO', 'CSD de la propia Empresa'), ('PROVEEDOR', 'CSD de Proveedor Crítico')], default='PROPIETARIO', max_length=32)),
                ('estatus', models.CharField(choices=[('ACTIVA', 'Activa (CSD Suspendido/En Riesgo)'), ('ACLARACION', 'Caso de Aclaración Ingresado'), ('RESUELTA', 'Resuelta (CSD Reactivado)'), ('REVOCADO', 'Cancelación Definitiva')], default='ACTIVA', max_length=32)),
                ('fecha_deteccion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('oficio_sat', models.CharField(blank=True, help_text='Número de oficio notificado por el SAT', max_length=64)),
                ('motivo_presuncion', models.TextField(blank=True, help_text='Fracción del 17-H Bis invocada y detalles')),
                ('acciones_tomadas', models.TextField(blank=True, help_text='Bitácora de seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_csd', to='materialidad.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_csd', to='materialidad.proveedor')),
            ],
            options={
                'verbose_name': 'Alerta CSD',
                'verbose_name_plural': 'Alertas CSD',
                'db_table': 'materialidad_alerta_csd',
                'ordering': ('-fecha_deteccion',),
            },
        ),
    ]
