# Generated by Django 5.0.2 on 2026-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0043_alertacsd'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciamaterial',
            name='estatus_revision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada')], default='PENDIENTE', max_length=16),
        ),
        migrations.AddField(
            model_name='evidenciamaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evidenciamaterial',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciamaterial',
            name='validado_por_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='evidenciamaterial',
            index=models.Index(fields=['estatus_revision', 'created_at'], name='materialid_status_cr_idx'),
        ),
    ]
