# Generated by Django 5.0.2 on 2026-03-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0045_alertaoperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('archivo', models.FileField(upload_to='cotizaciones/%Y/%m/')),
                ('archivo_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('texto_extraido', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=16)),
                ('error_detalle', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_pdf', to='materialidad.empresa')),
            ],
            options={
                'verbose_name': 'Cotización PDF',
                'verbose_name_plural': 'Cotizaciones PDF',
                'db_table': 'materialidad_cotizacion_pdf',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CotizacionConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=19)),
                ('importe', models.DecimalField(decimal_places=4, max_digits=19)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('unidad', models.CharField(blank=True, default='', max_length=64)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='materialidad.cotizacionpdf')),
            ],
            options={
                'verbose_name': 'Concepto de cotización',
                'verbose_name_plural': 'Conceptos de cotización',
                'db_table': 'materialidad_cotizacion_concepto',
                'ordering': ('cotizacion', 'orden'),
            },
        ),
        migrations.CreateModel(
            name='ComparativoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del comparativo', max_length=255)),
                ('notas', models.TextField(blank=True, default='')),
                ('resultado_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparativos', to='materialidad.empresa')),
                ('cotizaciones', models.ManyToManyField(blank=True, related_name='comparativos', to='materialidad.cotizacionpdf')),
            ],
            options={
                'verbose_name': 'Comparativo de precio',
                'verbose_name_plural': 'Comparativos de precio',
                'db_table': 'materialidad_comparativo_precio',
                'ordering': ('-created_at',),
            },
        ),
    ]
