# Generated by Django 5.0.2 on 2026-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0046_cotizacionpdf_cotizacionconcepto_comparativoprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio'), ('CAPACIDAD_PROVEEDOR', 'Capacidad del proveedor'), ('FECHA_CIERTA', 'Fecha cierta')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deliverablerequirement',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio'), ('CAPACIDAD_PROVEEDOR', 'Capacidad del proveedor'), ('FECHA_CIERTA', 'Fecha cierta')], default='ENTREGABLES', max_length=32),
        ),
        migrations.AlterField(
            model_name='operacionentregable',
            name='pillar',
            field=models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio'), ('CAPACIDAD_PROVEEDOR', 'Capacidad del proveedor'), ('FECHA_CIERTA', 'Fecha cierta')], default='ENTREGABLES', max_length=32),
        ),
    ]
