# Generated by Django 5.0.2 on 2026-03-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0050_legalcorpusupload_and_source_vector_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legalcorpusupload',
            new_name='materialida_autorid_28442b_idx',
            old_name='materialida_autori_1b02b5_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcorpusupload',
            new_name='materialida_estatus_6c70c0_idx',
            old_name='materialida_estatu_81525c_idx',
        ),
        migrations.RenameIndex(
            model_name='legalcorpusupload',
            new_name='materialida_es_vige_6e8214_idx',
            old_name='materialida_es_vig_b57207_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_ordenam_36bf79_idx',
            old_name='materialida_ordena_6226c5_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_corpus__21f0ef_idx',
            old_name='materialida_corpus__44a538_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_es_vige_eaaaac_idx',
            old_name='materialida_es_vig_c73477_idx',
        ),
        migrations.RenameIndex(
            model_name='legalreferencesource',
            new_name='materialida_estatus_fa877b_idx',
            old_name='materialida_estatu_bdd87a_idx',
        ),
    ]
