# Generated by Django 5.0.2 on 2026-03-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0054_auditmaterialitydossierversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_gasto', models.CharField(blank=True, default='', max_length=128)),
                ('origen', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], default='AUTO', max_length=16)),
                ('estado_general', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETO', 'Completo')], default='PENDIENTE', max_length=16)),
                ('progreso_porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_asignadas', to='materialidad.checklist')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_operativos', to='materialidad.operacion')),
            ],
            options={
                'db_table': 'materialidad_operacion_checklist',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperacionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('ENTREGABLES', 'Entregables'), ('RAZON_NEGOCIO', 'Razón de negocio'), ('CAPACIDAD_PROVEEDOR', 'Capacidad del proveedor'), ('FECHA_CIERTA', 'Fecha cierta')], max_length=32)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('requerido', models.BooleanField(default=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETO', 'Completo')], default='PENDIENTE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_items', to='materialidad.checklistitem')),
                ('operacion_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materialidad.operacionchecklist')),
            ],
            options={
                'db_table': 'materialidad_operacion_checklist_item',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='operacionchecklist',
            index=models.Index(fields=['operacion', 'estado_general'], name='op_check_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='operacionchecklist',
            constraint=models.UniqueConstraint(fields=('operacion', 'checklist'), name='op_checklist_unique_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionchecklistitem',
            index=models.Index(fields=['operacion_checklist', 'estado'], name='op_check_item_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionchecklistitem',
            index=models.Index(fields=['pillar', 'estado'], name='op_check_pillar_estado_idx'),
        ),
    ]
