# Generated by Django 5.0.2 on 2025-12-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenant_aiconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
    ]
